# /etc/pacman.conf - Linux Scaracle x86_64

[options]
HoldPkg     = pacman glibc
Architecture = auto
Color
CheckSpace
VerbosePkgLists
ParallelDownloads = 5

SigLevel    = Optional TrustAll
LocalFileSigLevel = Optional

# REPOSITORI RESMI SCARACLE
[scaracle]
Server = https://raw.githubusercontent.com/scaracle-os/scaracle-repo/main/$arch
